# Generated by Django 3.2.1 on 2021-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryingjwt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
